### ISSUE TITLE
Documentation Text Cut-off

### ISSUE THREAD

**Issue by swiftfish** [web2py/py4web#277]
Most pages of documentation text are getting hidden on the right side. It may be the no.css overflow-x setting:

``` css
html, body {
  max-width: 100vw;
  overflow-x: hidden;
  box-sizing: border-box;
}
```

Only #chapter-00 and #chapter-07 display the entire page without the right side being cutoff.
